---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: psclusters.planetscale.com
spec:
  group: planetscale.com
  names:
    kind: PsCluster
    listKind: PsClusterList
    plural: psclusters
    singular: pscluster
  scope: Namespaced
  version: v1alpha1

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etcd-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: etcd-operator
    spec:
      imagePullSecrets:
        - name: psregistry       
      containers:
      - name: etcd-operator
        #image: quay.io/coreos/etcd-operator:latest
        image: registry.planetscale.com/etcd/etcd-operator:latest
        imagePullPolicy: IfNotPresent
        command:
        - etcd-operator
        # Uncomment to act for resources in all namespaces. More information in doc/clusterwide.md
        #- -cluster-wide
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etcd-backup-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: etcd-backup-operator
    spec:
      imagePullSecrets:
        - name: psregistry       
      containers:
      - name: etcd-backup-operator
        #image: quay.io/coreos/etcd-operator:latest        
        image: registry.planetscale.com/etcd/etcd-operator:latest        
        command:
        - etcd-backup-operator
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etcd-restore-operator
  labels:
    name: etcd-restore-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: etcd-restore-operator
    spec:
      imagePullSecrets:
        - name: psregistry       
      containers:
      - name: etcd-restore-operator
        #image: quay.io/coreos/etcd-operator:latest
        image: registry.planetscale.com/etcd/etcd-operator:latest                
        command:
        - etcd-restore-operator
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: planetscale-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: planetscale-operator
  template:
    metadata:
      labels:
        name: planetscale-operator
    spec:
      imagePullSecrets:
        - name: psregistry 
      containers:
        - name: planetscale-operator
          image: registry.planetscale.com/planetscale/operator:latest
          command:
          - planetscale-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-operator
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: prometheus-operator
  name: prometheus-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: prometheus-operator
    spec:
      containers:
      - args:
        - --kubelet-service=kube-system/kubelet
        - --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
        image: quay.io/coreos/prometheus-operator:v0.28.0
        name: prometheus-operator
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: prometheus-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus

